텐서 생성 및 변환

In [3]:
import torch
print(torch.tensor([[1,2], [3,4]]))
print(torch.tensor([[1,2], [3,4]], device='cuda:0'))
print(torch.tensor([[1,2], [3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


텐서를 ndarray로 변환

In [7]:
temp = torch.tensor([[1,2], [3,4]])
print(temp.numpy())
temp = torch.tensor([[1,2], [3,4]], device='cuda:0')
print(temp.to('cpu').numpy()) # -> GPU상의 텐서를 CPU텐서로 변환한 후 ndarray로 변환해야함

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


텐서의 인덱스 조작

In [8]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0], temp[1], temp[-1]) # -> 인덱스로 접근
print('------------------------')
print(temp[2:5], temp[4:-1]) # -> 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


텐서 연산 및 차원 조작

In [10]:
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])
print(v - w) # -> 길이가 같은 벡터간 뺄셈
print(v + w) # -> 길이가 같은 벡터간 덧셈

tensor([-2, -2, -3])
tensor([4, 6, 9])


In [15]:
temp = torch.tensor([[1,2], [3,4]]) # -> 2x2 행렬 생성
print(temp.shape)
print('------------------------')
print(temp.view(4, 1)) # -> 2x2 행렬을 4x1로 변형
print('------------------------')
print(temp.view(-1)) # -> 2x2 행렬을 1차원 벡터로 변형
print('------------------------')
print(temp.view(1, -1)) # -> -1은 (1, ?)와 같은 의미로 다른 차원으로부터 해당 값을 유추하겠다는 뜻. temp의 원소개수(2x2=4)를 유지한채 (1, ?)의 형태를 만족해야 하므로 (1,4)를 의미
print('------------------------')
print(temp.view(-1, 1)) # -> (?, 1)과 같은 의미로 temp의 원소개수(2x2=4)를 유지한채 (?, 1)의 형태를 만족해야 하므로 (4,1)을 의미

torch.Size([2, 2])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
------------------------
tensor([1, 2, 3, 4])
------------------------
tensor([[1, 2, 3, 4]])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
